[package]
name = "typ-McQs"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["MuhammadAly11"]
license = "MIT"
description = "Typst template for McQ exams"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "template/thumbnail.png"
